included:
  - nBack/
excluded:
  - Pods/
disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - file_length
  - variable_name
  - function_parameter_count
